apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: toms-hygieia-api
    name: toms-hygieia-api
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: toms-hygieia-api
      app.kubernetes.io/component: toms-hygieia-api
      app.kubernetes.io/instance: toms-hygieia-api
    name: toms-hygieia-api
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: toms-hygieia-api:latest
    source:
      git:
        uri: https://github.com/Hygieia/api
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java:8
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: toms-hygieia-api
      app.kubernetes.io/component: toms-hygieia-api
      app.kubernetes.io/instance: toms-hygieia-api
    name: toms-hygieia-api
  spec:
    replicas: 1
    selector:
      deploymentconfig: toms-hygieia-api
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: toms-hygieia-api
      spec:
        containers:
        - env:
          - name: SPRING_DATA_MONGODB_HOST
            value: mongo-hygieia
          image: ''
          name: toms-hygieia-api
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - toms-hygieia-api
        from:
          kind: ImageStreamTag
          name: toms-hygieia-api:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: toms-hygieia-api
      app.kubernetes.io/component: toms-hygieia-api
      app.kubernetes.io/instance: toms-hygieia-api
    name: toms-hygieia-api
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: toms-hygieia-api
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: toms-hygieia-api
      app.kubernetes.io/component: toms-hygieia-api
      app.kubernetes.io/instance: toms-hygieia-api
      app.kubernetes.io/name: toms-hygieia-api
    name: toms-hygieia-api
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: toms-hygieia-api
      weight: 100
    tls:
      termination: Edge
      insecureEdgeTerminationPolicy: Redirect